### ISSUE TITLE
Battle Box music plays too early

### ISSUE THREAD

**Issue by RuiNtD** [AsoDesu/IslandUtils#17]
The Battle Box music plays way too early every round. It's also worth noting that MCC Island's "Starting in" music doesn't seem to play, but I'm unsure if this is because of MCCI or Island Utils. Possibly related?

https://user-images.githubusercontent.com/1149870/189960863-25b60b84-2c4b-469e-a123-06c30cd308a7.mp4

https://user-images.githubusercontent.com/1149870/189960846-fac1d7b7-8367-46aa-b8a7-3a074e246193.mp4

**Comment by hugge64** [comment]
My battle box music starts at 00:10 as it should, but idk why yours starts at 00:02. And the Starting in music in Battle Box is actually the Battle box music, not the original Starting in music as you can see in the MCC event.
Scroll to 2:22:29 - There you will hear that it's the Battle Box music that plays instead of the original Starting in music- https://www.youtube.com/watch?v=0MC-ieK3BME

I apologize if you don't understand, I'm Swedish and I'm not very good at writing in English xD

**Comment by LukynkaCZE** [comment]
Weird, its supposed to play at 00:10 as that's when the music starts in the actual event but yours play at 00:02 for some reason. I will look into it
