### ISSUE TITLE
Tgttosawaf option 

### ISSUE THREAD

**Issue by UltraTeal** [AsoDesu/IslandUtils#63]
If it it possible make it so the chickens in tggttos are players to make it feel more like the event but of course make the hit boxes the same as the chickens to make it fair to others

**Comment by AsoDesu** [comment]
Cannot implement since the player hitbox is significantly larger than then chicken hitbox and there really isn't a way around that,
I could make the hitbox smaller, however that'll just make hitting them more difficult because the real hitbox is smaller than the apparent hitbox 
Thank you for the suggestion :D
